---
title: "Internship report"
subtitle: "Spatial components"
author: "Ludovic Moisan"
supervisors: "Pierre aumond, Paul Chapron, Nicolas Roelandt"
date: "`r Sys.Date()`"
output: 
  html_document :
    theme: united
editor_options: 
  chunk_output_type: console
---

#FILE NOT FINISHED AND NOT MEANT TO BE RUN AS IS.
#USE OF ABSOLUTE PATHS AND MANY LIBRARY IMPORTS FOR TESTING AND COMPARING METHODS.


```{r library-sunrise, include=FALSE}

library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rgdal)
library(geojsonsf)
library(geosphere)
library(sf)
library(raster)
library(leaflet)
library(stringr)
library(RANN)

library(shiny)

library(mathart)
library(SPODT)
library(CART)

library(tree)

library(ClustGeo)

```

```{r setup-data-spatial, include = FALSE}

here::i_am("vignettes/[Computing]Spatial_components.Rmd")

if(!exists("all_info_sun")){
  if(!file.exists(here::here("data","all_info_sun.rds"))){
    URL2 <- "https://zenodo.org/record/6536129/files/time_after_sunrise.rds?download=1"
    all_info_sun <- readRDS(url(URL2))
    saveRDS(all_info_sun,here::here("data","all_info_sun.rds"))
  }
  else{
  all_info_sun <- readRDS(here::here("data","all_info_sun.rds"))
  }
}

france_info <- all_info_sun %>% filter(admin=="France")

```

```{r download-data-spatial, include = FALSE}

if(!exists("bars_fr")){
  if(!file.exists(here::here("raw_data","osm-fr-bars.geojson"))){
    URL_bar <- "https://babel.opendatasoft.com/explore/dataset/osm-fr-bars/download/?format=geojson&timezone=Europe/Berlin&lang=fr"
    bars_fr <- geojson_sf(URL_bar)
    st_write(bars_fr,here::here("raw_data","osm-fr-bars.geojson"))
  }
  else{
  bars_fr <- geojson_sf(here::here("raw_data","osm-fr-bars.geojson"))
  }
}
# 
# if(!exists("rest_fr")){
#   if(!file.exists(here::here("raw_data","osm-restaurant-fr.geojson"))){
#     URL_rest <- "https://babel.opendatasoft.com/explore/dataset/osm-restaurant-fr/download/?format=geojson&timezone=Europe/Berlin&lang=fr"
#     rest_fr = geojson_sf(URL_rest)
#     st_write(rest_fr,here::here("raw_data","osm-restaurant-fr.geojson"))
#   }
#   else{
#   rest_fr <- geojson_sf(here::here("raw_data","osm-restaurant-fr.geojson"))
#   }
# }
# 
# if(!exists("school_fr")){
#   if(!file.exists(here::here("raw_data","osm-fr-ecoles.geojson"))){
#     URL_school <- "https://babel.opendatasoft.com/explore/dataset/osm-fr-ecoles/download/?format=geojson&timezone=Europe/Berlin&lang=fr"
#     school_fr = geojson_sf(URL_school)
#     st_write(school_fr,here::here("raw_data","osm-fr-ecoles.geojson"))
#   }
#   else{
#   school_fr <- geojson_sf(here::here("raw_data","osm-fr-ecoles.geojson"))
#   }
# }
# 
# #Download Metropolitain France's geometry
# if(!exists("france_metro")){
#   if(!file.exists(here::here("raw_data","2020_France_metro_WGS84.geojson"))){
#     URLfr <- "https://github.com/nicolas-roelandt/lasso-data-analysis/raw/main/raw_data/2020_France_metro_WGS84.geojson"
#     france_metro <- geojson_sf(URLfr)
#     st_write(france_metro,here::here("raw_data","2020_France_metro_WGS84.geojson"))
#   }
#   else{
#   france_metro <- geojson_sf(here::here("raw_data","2020_France_metro_WGS84.geojson"))
#   }
# }
# 
if(!exists("communes_fr")){
  if(!file.exists(here::here("raw_data","georef-france-commune.geojson"))){
    URL_communes <- "https://public.opendatasoft.com/explore/dataset/georef-france-commune/download/?format=geojson&timezone=Europe/Berlin&lang=fr"
    communes_fr = geojson_sf(URL_communes)
    st_write(communes_fr,here::here("raw_data","georef-france-commune.geojson"))
  }
  else{
  communes_fr <- geojson_sf(here::here("raw_data","georef-france-commune.geojson"))
  }
}
# 
# 
if(!exists("pop_fr")){
  if(!file.exists(here::here("data","pop_fr.rds"))){
    URL_pop <- "https://zenodo.org/record/6554256/files/base-pop-historiques-1876-2019.csv?download=1"
    pop_fr <- read.csv2(URL_pop, header = TRUE)
    saveRDS(pop_fr, here::here("data","pop_fr.rds"))
  }
  else{
  pop_fr <- readRDS(here::here("data","pop_fr.rds"))
  }
}

# if(!exists("carroye_pop_fr")){
#   if(!file.exists(here::here("raw_data/shapefile_pop","Filosofi2015_carreaux_200m_metropole.shp"))){
#     print("not implemented yet")
#   }
#   else{
#   carroye_pop_fr <- read_sf(here::here("raw_data/shapefile_pop","Filosofi2015_carreaux_200m_metropole.shp"))
#   }
# }


```

```{r carroye, echo = FALSE, eval = FALSE}

carroye_pop_fr <- read_sf("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/raw_data/shapefile_pop/Filosofi2015_carreaux_200m_metropole.shp")

bars_fr <- read_sf("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/raw_data/osm-fr-bars.geojson")

carroye_pop_fr <- st_transform(carroye_pop_fr, crs = st_crs("EPSG:4326"))

intersection <- st_intersection(carroye_pop_fr,bars_fr)


ggplot() + 
  geom_sf(data = carroye_pop_fr, size = 1, color = "black", fill = "cyan1") + 
  ggtitle("AOI Boundary Plot") + 
  coord_sf()

leaflet(carroye_pop_fr) %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(fillColor = "ind", weight = 0.1,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))

```

```{r pop-dataset, echo = FALSE, eval = FALSE}

str(pop_fr)
str(communes_fr)
# Data of all french cities, including dromcom territories
city_pop <- sf::st_as_sf(inner_join(pop_fr %>% select(CODGEO,PMUN19),communes_fr %>% select(com_code,geo_point_2d,geometry), 
                          by=c("CODGEO" = "com_code")))

str(city_pop)
# Only select french cities in metropolitain territory
# Pop column in original dataset is string coded and has spaces, we need to get rid of them and then convert to num
city_pop_fr <- st_intersection(city_pop,france_metro) %>% 
  dplyr::mutate(PMUN19 = as.numeric(str_replace_all(PMUN19, "\\s+", "")),pop_norm = (PMUN19-min(PMUN19))/(max(PMUN19)-min(PMUN19)))

dt<-sample(2, nrow(city_pop_fr), replace = TRUE, prob=c (0.05,0.2))
train_df <- city_pop_fr[dt==1,]

str(city_pop_fr)

leaflet(city_pop_fr) %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(fillColor = "red", fillOpacity = "pop_norm", weight = 0.2,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))


```

```{r pop-visualisation, echo = FALSE}



```

```{r tag-visualisation, echo=FALSE}

all_info_tempo <- readRDS("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/data/all_info_tempo.rds")

pal <- colorNumeric(palette = "RdYlBu", domain = all_info_tempo$pleasantness)

ui = fluidPage(
  sidebarPanel(selectInput(inputId = "tag_name", "Tag Name", choices = sort(unique(all_info_tempo$tag_name)),selected = "chatting")),
  leafletOutput(outputId = "map", height = 600, width = 800)
  )

server = function(input, output) {
  output$map = renderLeaflet({
    leaflet(data = all_info_tempo[(all_info_tempo$tag_name) == input$tag_name, ] %>% filter(admin == "France")) %>%
      setView(lat = 46.62, lng = 2.55, zoom = 6) %>% #To focus on France on opening, can be changed or disabled
      addTiles() %>% addProviderTiles(providers$CartoDB.Positron) %>%
      addCircleMarkers(lng = ~lon, lat = ~lat, stroke = FALSE, fillOpacity = 0.8, color = ~pal(pleasantness),
                   radius = 6, 
                   clusterOptions = markerClusterOptions(spiderfyOnMaxZoom = FALSE, maxClusterRadius = 60, disableClusteringAtZoom = 12),
                   popup = ~leafpop::popupTable(all_info_tempo,
                                       zcol = c("pk_track", "noise_level", "pleasantness"),
                                       row.numbers = FALSE, feature.id = FALSE)) %>%
      addLegend(position = "bottomright",
            pal = pal, values = ~pleasantness, opacity = 1)})
  
}
shinyApp(ui, server)

```

```{r density-map, include = FALSE}

all_info_tempo <- readRDS("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/data/all_info_tempo.rds")
meteo <- readRDS("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/data/meteo_france.rds")
france <- geojson_sf("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/raw_data/2020_France_metro_WGS84.geojson")
communes <- geojson_sf("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/raw_data/georef-france-commune.geojson")
bars_fr <- geojson_sf("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/raw_data/osm-fr-bars.geojson")
pop <- readRDS("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/data/pop_fr.rds")

pop_fr <- pop %>% dplyr::select(com_code = CODGEO, PMUN19)
pop_fr[nrow(pop_fr) + 1,] = c("75056","2160928")

pop_fr <- pop_fr %>% dplyr::mutate(PMUN19 = as.numeric(str_replace_all(PMUN19, "\\s+", "")))

communes_fr <- st_transform(sf::st_intersection(communes,france), crs= st_crs("EPSG:2154"))
communes_fr <- communes_fr[rowSums(is.na(communes_fr)) != ncol(communes_fr), ]

communes_sp <- as_Spatial(communes_fr)
bars_sp <- as_Spatial(st_transform(bars_fr,crs= st_crs("EPSG:2154")))

bars_communes <- sp::over(bars_sp,communes_sp)

communes_bars <- data.frame(table(bars_communes$com_code)) %>% dplyr::rename(com_code = Var1, bars_nb = Freq)

communes_fr_bar <- left_join(communes_fr,communes_bars) %>% left_join(pop_fr) %>% 
  mutate(bar_by_hab = bars_nb/PMUN19, hab_by_bar = PMUN19/bars_nb, surface = st_area(geometry), bar_kmsq = surface/bars_nb/1000000)

communes_fr_bar_lot <- left_join(communes_fr,communes_bars) %>% left_join(pop_fr) %>% dplyr::filter(PMUN19 > 2000) %>%
  mutate(bar_by_hab = bars_nb/PMUN19, hab_by_bar = PMUN19/bars_nb, surface = st_area(geometry), bar_kmsq = surface/bars_nb/1000000)

plot(communes_fr_bar["bar_by_hab"], border = NA, main = "Bars par habitant")
plot(communes_fr_bar_lot["bar_by_hab"], border = NA, title(main = "Bars par habitant", sub = "Villes de plus de 2000 habitants"))

```

```{r test_spatial, include = FALSE}

# df_fr <- all_info_tempo %>% dplyr::filter(admin == "France")
# 
# test <- df_fr %>% distinct(pk_track, .keep_all= TRUE)
# 
# kdt_res <- mathart::kdtree(test %>% dplyr::mutate(x = lon,y = lat))
# 
# ggplot() +
#   geom_segment(aes(x, y, xend = xend, yend = yend), kdt_res)

df_fr <- all_info_tempo %>% dplyr::filter(admin == "France")

test <- df_fr %>% distinct(pk_track, .keep_all= TRUE)

coord_tag <- test %>% dplyr::select(c(tag_name,lon,lat))

DT_sf <- st_as_sf(test, coords = c("lon", "lat"), 
                 crs = 4326)

x <- nn2(test %>% dplyr::select(x = lon,y = lat), k = 20, treetype = "kd")

matrix_coord <- x[["nn.idx"]]

df_coord <- data.frame(matrix(nrow = nrow(matrix_coord), ncol = ncol(matrix_coord)))

for(n in (1:nrow(DT_sf))){
  df_coord[matrix_coord==n] <- DT_sf[n,]$geometry
}

df_coord <- st_as_sf(df_coord)

for(n in (1:nrow(df_coord))){
  df_coord[n,]$box <- st_bbox(df_coord[n,])
}


#df_coord <- df_coord %>% dplyr::mutate(group = row.names(df_coord))

# ggplot() + geom_sf(data=df_coord)
# ggplot() + geom_sf(data=df_coord, aes(color = group))


coord_tag <- all_info_tempo %>% dplyr::filter(admin == "France") %>% dplyr::select(c(tag_name,lon,lat))

tree_test <- tree::tree(tag_name ~., data = coord_tag, control = tree.control(dim(coord_tag)[1]))

plot(tree_test)

# 
# spodt.results <- spodt(time_length ~ 1, data = sp_test)
# 
# spodt.tree(spodt.results)
# 
# SSL.result <- spodtSpatialLines(spodt.results, sp_test)
# plot(SSL.result)
# points(sp_test, cex = log(sp_test@data$time_length * 10))



df_fr <- all_info_tempo %>% dplyr::filter(admin == "France")

test <- df_fr %>% distinct(pk_track, .keep_all= TRUE)

y <- partitions::kdTree(test)



df_chat_fr <- all_info_tempo %>% dplyr::filter(admin == "France" & tag_name == "chatting") %>% dplyr::select(pk_track,lon,lat)

DT_sf <- st_as_sf(df_chat_fr, coords = c("lon", "lat"), crs = 4326)

library(SearchTrees)

quad <- SearchTrees::createTree(df_chat_fr)

library(quadtree)
library(raster)

rasterFromXYZ(xyz = df_chat_fr)


carroye <- read_sf("C:/Users/moisan/Documents/Stage/github/lasso-data-analysis/raw_data/shapefile_pop/Filosofi2015_carreaux_200m_metropole.shp")

library(RapidPolygonLookup)

chat_fr <- RapidPolygonLookup(DT_sf, carroye, poly.list = NULL, k = 10, N = nrow(DT_sf), 
    poly.id = "fips", poly.id.colname = "census.block", keep.data = TRUE, 
    verbose = 0)



```



