---
title: "Internship report"
subtitle: "Load main components"
author: "Ludovic Moisan"
supervisors: "Pierre aumond, Paul Chapron, Nicolas Roelandt"
date: "`r Sys.Date()`"
output: 
  html_document :
    theme: united
editor_options: 
  chunk_output_type: console
---

```{r library-components, include=FALSE}

library(here)

```

```{r load-main-components, include = FALSE}

here::i_am("vignettes/Load_main_components.Rmd")

if(!exists("all_info")){
  if(!file.exists(here("data","all_info.rds"))){
    URL <- "https://zenodo.org/record/6536129/files/all_info.rds?download=1"
    all_info <- readRDS(url(URL))
    saveRDS(all_info,here("data","all_info.rds"))
  }
  else{
  all_info <- readRDS(here("data","all_info.rds"))
  }
}

if(!exists("all_info_sun")){
  if(!file.exists(here("data","all_info_sun.rds"))){
    URL2 <- "https://zenodo.org/record/6536129/files/time_after_sunrise.rds?download=1"
    all_info_sun <- readRDS(url(URL2))
    saveRDS(all_info_sun,here("data","all_info_sun.rds"))
  }
  else{
  all_info_sun <- readRDS(here("data","all_info_sun.rds"))
  }
}

```